### ISSUE TITLE
Results on CUB dataset

### ISSUE THREAD

**Issue by daiqing7** [lisadunlap/LADS#17] opened 2023-04-12 08:18 UTC
May I ask if the evaluation or dataset setting of CUB experiments in this code are consistent with the paper's? 

My reproduced results are:
64.75 (OOD)
86.02 (ID)
75.118 (Extended)

The OOD result is obviously lower than reported 66.18± 0.25%.

 Many thanks!

**Comment by lisadunlap** [comment] 2023-04-12 15:08
Ah that does seem quite off, you are using the default configs correct? I can rerun today to see what the problem may be

**Comment by daiqing7** [comment] 2023-04-12 15:24
> Ah that does seem quite off, you are using the default configs correct? I can rerun today to see what the problem may be, there is a chance that I uploaded the wrong config file.

Thanks!! Yes, I run the model with `python main.py --config configs/CUB/lads.yaml`

BTW, the results on DomainNetMini are okay.

**Comment by lisadunlap** [comment] 2023-04-13 00:28
Okay looks like I'm getting 65.67, here's the [wandb link](https://wandb.ai/lisadunlap/testing_lads_public_repo)

If you're still having issues, feel free to send me a link to your run and I can try to debug

**Comment by tsun** [comment] 2023-04-13 02:38
I reproduced CUB results without using embedding provided in the repo, and found a few interesting points that might be helpful.

1. The default hyperparameters from current configs are slightly different from Supp.A. In particular, Aug LR is 0.1 in the config but 0.001 in the paper. Using 0.1 performs slightly better in my end.

2. Aug WD seems to have a high influence on the performance (all w/ Aug LR=0.1, interesting) 
     Aug WD=0.05       --- 64.97±0.60      86.12±0.24    75.54±0.41
     Aug WD=0.005     --- 65.88±0.47    86.22±0.21    76.05±0.52
     Aug WD=0.0005   --- 66.44±0.48    86.35±0.19    76.39±0.19
I guess the learned quality of augmentation network is critical.

**Comment by daiqing7** [comment] 2023-04-13 05:08
> Okay looks like I'm getting 65.67, here's the [wandb link](https://wandb.ai/lisadunlap/testing_lads_public_repo)
> 
> If you're still having issues, feel free to send me a link to your run and I can try to debug

@lisadunlap 

Thanks for your help!

Here are my reproduced results: https://wandb.ai/daiqing-uva/LADS_CUB_Replication/table

It seems that @tsun gets 64.97±0.60, which is close to my reproduced results: 64.75.

**Comment by daiqing7** [comment] 2023-04-13 06:44
> I reproduced CUB results without using embedding provided in the repo, and found a few interesting points that might be helpful.
> 
> 1. The default hyperparameters from current configs are slightly different from Supp.A. In particular, Aug LR is 0.1 in the config but 0.001 in the paper. Using 0.1 performs slightly better in my end.
> 2. Aug WD seems to have a high influence on the performance (all w/ Aug LR=0.1, interesting)
>    Aug WD=0.05       --- 64.97±0.60      86.12±0.24    75.54±0.41
>    Aug WD=0.005     --- 65.88±0.47    86.22±0.21    76.05±0.52
>    Aug WD=0.0005   --- 66.44±0.48    86.35±0.19    76.39±0.19
>    I guess the learned quality of augmentation network is critical.

@tsun I have similar results with yours (64~65), may I ask the domain consistency score? My class consistency acc is around 35%, which is obviously lower than 50%.

**Comment by lisadunlap** [comment] 2023-04-22 22:58
@daiqing7 I pushed the new version of the code as well as updated the precomputed embeddings earlier this week that I have verified work on my end. If you are still having trouble reproducing results, please let me know. I'm going to close this issue for now

**Closed by lisadunlap** 2023-04-22 22:58 UTC
